services:
  scrapers:
    build: ./scrapers
    ports:
      - 8080:80
    cap_add:
      - SYS_ADMIN
    environment:
      - PORT=80
      - headless=true

  redis:
    image: docker.io/bitnami/redis:6.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL

    command: redis-server --requirepass "123456789"

    volumes:
      - "redis_data:/bitnami/redis/data"

volumes:
  redis_data:
    driver: local
